version: "3.9"
services: 
    db:
        image: mysql:5.7
        container_name: "mysql"
        restart: always
        ports: 
            - "3307:3306"
        volumes: 
            - ./Database:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: "CupidSelepituninu*999"
            MYSQL_USER: "myroot"
            MYSQL_PASSWORD: "myroot"
            MYSQL_DATABASE: "payroll"    
    web:
        container_name: "web"
        build: .
        ports: 
            - "8000:80"
        volumes: 
            - .:/var/www/html
        depends_on: 
            - db
        environment: 
            - PMA_HOST=localhost